"use client"
import { useEffect, useState } from "react"
import { getSprintReport } from "@/lib/api"
import { Btn, Spinner, Card } from "@/components/shared/ui"
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from "recharts"
import type { SprintReport } from "@/types"

export function ManagerReport() {
  const [report, setReport] = useState<SprintReport | null>(null)
  const [loading, setLoading] = useState(false)
  const [generated, setGenerated] = useState(false)

  const load = async () => {
    setLoading(true)
    try {
      const data = await getSprintReport()
      setReport(data)
      setGenerated(true)
    } catch {}
    setLoading(false)
  }

  useEffect(() => { load() }, [])

  const velocityColor = (v: number) =>
    v >= 80 ? "#25cc1d" : v >= 60 ? "#f5a623" : "#ff4f4f"

  return (
    <div className="animate-fade-in">
      <div className="flex items-center justify-between mb-5">
        <div>
          <h1 className="text-[20px] font-semibold">Manager Report</h1>
          <p className="text-[13px] text-[var(--text-muted)] mt-0.5">Auto-generated by Manager Agent — ready to share</p>
        </div>
        <Btn onClick={load} disabled={loading} variant="primary">
          {loading ? <><Spinner /> Generating...</> : "⚡ Refresh Report"}
        </Btn>
      </div>

      {loading && !report && (
        <div className="flex items-center gap-3 p-4 bg-[var(--green-faint)] border border-[var(--border)] rounded-xl text-[13px] text-[var(--green)]">
          <Spinner /> Manager Agent compiling sprint insights...
        </div>
      )}

      {report && (
        <div className="flex flex-col gap-4">
          {/* Velocity + summary */}
          <div className="grid grid-cols-4 gap-3">
            <div className="bg-[var(--card)] border border-[var(--border-muted)] rounded-xl p-4 text-center">
              <div className="mono text-[9px] text-[var(--text-dim)] uppercase tracking-wider mb-2">Velocity</div>
              <div className="text-3xl font-bold" style={{ color: velocityColor(report.velocity_percent) }}>
                {report.velocity_percent}%
              </div>
            </div>
            <div className="bg-[var(--card)] border border-[var(--border-muted)] rounded-xl p-4 text-center">
              <div className="mono text-[9px] text-[var(--text-dim)] uppercase tracking-wider mb-2">Total Tasks</div>
              <div className="text-3xl font-bold text-[var(--text)]">{report.total_tasks}</div>
            </div>
            <div className="bg-[var(--card)] border border-[var(--border-muted)] rounded-xl p-4 text-center">
              <div className="mono text-[9px] text-[var(--text-dim)] uppercase tracking-wider mb-2">Done</div>
              <div className="text-3xl font-bold text-[var(--green)]">{report.done_tasks}</div>
            </div>
            <div className="bg-[var(--card)] border border-[var(--border-muted)] rounded-xl p-4 text-center">
              <div className="mono text-[9px] text-[var(--text-dim)] uppercase tracking-wider mb-2">Critical Risks</div>
              <div className="text-3xl font-bold text-[var(--red)]">{report.critical_risks}</div>
            </div>
          </div>

          {/* Workload chart */}
          {report.team_workloads.length > 0 && (
            <Card>
              <div className="text-[12px] font-semibold text-[var(--text)] mb-3 flex items-center gap-2">
                <span className="text-[var(--green)]">◉</span> Team Workload Distribution
              </div>
              <ResponsiveContainer width="100%" height={160}>
                <BarChart data={report.team_workloads} margin={{ top: 0, right: 0, bottom: 0, left: -20 }}>
                  <XAxis dataKey="name" tick={{ fill: "#636159", fontSize: 11 }} axisLine={false} tickLine={false}
                    tickFormatter={(v) => v.split(" ")[0]} />
                  <YAxis tick={{ fill: "#636159", fontSize: 10 }} axisLine={false} tickLine={false} domain={[0, 150]} />
                  <Tooltip
                    contentStyle={{ background: "#2e2d2d", border: "1px solid rgba(37,204,29,0.2)", borderRadius: 6, fontSize: 11, color: "#e8e8e0" }}
                    formatter={(v: number) => [`${v}%`, "Workload"]}
                  />
                  <Bar dataKey="workload" radius={[4, 4, 0, 0]}>
                    {report.team_workloads.map((entry, i) => (
                      <Cell
                        key={i}
                        fill={entry.workload >= 100 ? "#ff4f4f" : entry.workload >= 85 ? "#f5a623" : "#25cc1d"}
                      />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </Card>
          )}

          {/* Summary */}
          <div className="bg-[var(--card2)] border-l-4 border-l-[var(--green)] rounded-xl p-4">
            <div className="mono text-[9px] text-[var(--green)] uppercase tracking-wider mb-2">Executive Summary</div>
            <p className="text-[13px] text-[var(--text)] leading-relaxed">{report.executive_summary}</p>
          </div>

          {/* Key risks */}
          {report.key_risks.length > 0 && (
            <div className="bg-[var(--card2)] border-l-4 border-l-[var(--amber)] rounded-xl p-4">
              <div className="mono text-[9px] text-[var(--amber)] uppercase tracking-wider mb-2">Key Risks</div>
              <ul className="flex flex-col gap-1">
                {report.key_risks.map((r, i) => (
                  <li key={i} className="text-[13px] text-[var(--text)] flex items-start gap-2">
                    <span className="text-[var(--amber)] flex-shrink-0 mt-0.5">•</span> {r}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Recommendations */}
          {report.recommendations.length > 0 && (
            <div className="bg-[var(--card2)] border-l-4 border-l-[var(--blue)] rounded-xl p-4">
              <div className="mono text-[9px] text-[var(--blue)] uppercase tracking-wider mb-2">AI Recommendations</div>
              <ul className="flex flex-col gap-1">
                {report.recommendations.filter(Boolean).map((r, i) => (
                  <li key={i} className="text-[13px] text-[var(--text)] flex items-start gap-2">
                    <span className="text-[var(--green)] flex-shrink-0 mt-0.5">→</span> {r}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
